##script##
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("All Script", "GrapeTheme")

local Tab = Window:NewTab("Blox Fruits")
local Section = Tab:NewSection("HULK U HUB")
Section:NewButton("Execute Script", "ButtonInfo", function()
    loadstring(game:HttpGet"https://raw.githubusercontent.com/HULKUexe/HULK-UFree-Script/main/HULKUHUB")()
end)
local Section = Tab:NewSection("Power x Hub V2")
Section:NewButton("Execute Script", "ButtonInfo", function()
    _G.Color = Color3.fromRGB(178, 34, 33)
loadstring(game:HttpGet("https://raw.githubusercontent.com/PowerxCANDYYY/NaMo/main/BFPOWERXHUBv2.lua"))()
end)
local Section = Tab:NewSection("MUKURO")
Section:NewButton("Execute Script", "ButtonInfo", function()
    loadstring(game:HttpGet"https://raw.githubusercontent.com/xDepressionx/Free-Script/main/AllScript.lua")()
end)
local Section = Tab:NewSection("Nights")
Section:NewButton("Execute Script", "ButtonInfo", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/NightsTimeZ/Night_Script/main/AllGame.lua"))()
end)

local Tab = Window:NewTab("Pet Simulator X")
local Section = Tab:NewSection("[Project-Meow]")
Section:NewButton("Execute Script", "ButtonInfo", function()
    loadstring(game:HttpGet"https://rawscripts.net/raw/Project-Meow_421")()
end)
local Section = Tab:NewSection("Key: Naruto")
local Section = Tab:NewSection("[Petsi X]")
Section:NewButton("ButtonText", "ButtonInfo", function()
    loadstring(game:GetObjects("rbxassetid://8194485654")[1].Source)("Petsi-X")
end)
local Section = Tab:NewSection("[SAZA HUB]")
Section:NewButton("ButtonText", "ButtonInfo", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/kB7CVpBd"))()
end)
local Section = Tab:NewSection("[BlackTrap]")
Section:NewButton("ButtonText", "ButtonInfo", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/BdvUGb2q"))()
end)
local Section = Tab:NewSection("[MasterHub V2.1.7]")
Section:NewButton("ButtonText", "ButtonInfo", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/destylol/masterhubv311/itachi/Main.lua"))()
end)

local Tab = Window:NewTab("Arsenal")
local Section = Tab:NewSection("[Bolts Hub]")
Section:NewButton("Execute Script", "ButtonInfo", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/1201for/V.G-Hub/main/V.Ghub'))()
end)

local Tab = Window:NewTab("Da Hood")
local Section = Tab:NewSection("[Da Hub V.3]")
Section:NewButton("Execute Script   ", "ButtonInfo", function()
    getgenv().Toggle = "v"
getgenv().Intro = false
loadstring(game:HttpGet("https://raw.githubusercontent.com/NoUGotbannedlol/DaHubV3/main/Launch"))()
end)